model:
  key: your_secret_key_here
  analyze_prompt: prompts/analyze_prompt.txt
  extract_prompt: prompts/extract_prompt.txt

data:
  raw_data: data/raw_data_healthcare.csv
  output_data: data/output.csv