"""
Use the module to extract topics from the comments
"""

from langchain.prompts import PromptTemplate
from langchain.chains import LLMChain


def gpt_analyze(comment, llm, analyze_prompt):
    """
    Analyze a comment using a specified language model and prompt template.

    Parameters:
    comment (str): The comment to be analyzed.
    llm (LLMModel): The language model to use for analysis.
    analyze_prompt (str): The prompt template to use for analysis.

    Returns:
    str: The analyzed text generated by the language model.
    """
    template = analyze_prompt

    prompt = PromptTemplate(template=template, input_variables=["comment"])
    llm_chain = LLMChain(prompt=prompt, llm=llm)
    answer = llm_chain(comment)
    return answer["text"]


def topic_extract(analysis, llm, extract_prompt):
    """
    Extract a topic from an analysis using a specified language model and prompt template.

    Parameters:
    analysis (str): The analysis from which a topic is to be extracted.
    llm (LLMModel): The language model to use for topic extraction.
    extract_prompt (str): The prompt template to use for topic extraction.

    Returns:
    str: The extracted topic generated by the language model.
    """
    template = extract_prompt

    prompt = PromptTemplate(template=template, input_variables=["analysis"])
    llm_chain = LLMChain(prompt=prompt, llm=llm)
    answer = llm_chain(analysis)
    return answer["text"]
